services:
  users-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ploshtadka-users-ms
    # env_file:
      # - .env
    environment:
      # fallback values if not provided via env_file
      DB_URL: ${DB_URL:-postgres://ploshtadka:ploshtadka@db:5432/ploshtadka}
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: ploshtadka-users-db
    environment:
      POSTGRES_DB: ploshtadka
      POSTGRES_USER: ploshtadka
      POSTGRES_PASSWORD: ploshtadka
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:

